import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientLayout from "../components/ClientLayout";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const dynamic = 'force-dynamic';

import { PermissionsProvider } from "../context/PermissionsContext";
import { ToastProvider } from "../components/Toast";
import { CompanyProvider } from "../context/CompanyContext";
import { ThemeProvider } from "../components/ThemeProvider";

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased" suppressHydrationWarning={true}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem={false}>
          <PermissionsProvider>
            <CompanyProvider>
              <ToastProvider>
                <ClientLayout>
                  {children}
                </ClientLayout>
              </ToastProvider>
            </CompanyProvider>
          </PermissionsProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
